{
 "title": "Tenant bottleneck",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\", container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{image!=\"\", container!=\"\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Failed requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(requests_total{status=\"error\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(requests_total)", "legendFormat": "__auto" }
   ]
  }
 ]
}